/*
aiglong4_anal.C file contains the analysis functions that allow to get out the informations from the Root file generated by Geant4 simulation.
These functions, which are based on the class 'Analyzer' defined in "Analyzer.h", create Root files containing histograms of the data of the simulation. 
*/

void analg4() 
{
  /*
  It creates histograms of: 
  - track multiplicity (number of tracks for each event);
  - charges of secondary nuclei;
  - kinetic energy distribution of secondary nulcei.
  */

  Analyzer* anal = new Analyzer(); 
  //  anal->SetFile("file.root");
  printf("set file chain\n");
  anal->SetFileChain("fichiers_test.txt");
  printf("set file chain retour\n");
  printf("init hist\n");
  anal->InitHisto();
  printf("init hist retour\n");
  printf("loop\n");
  anal->Loop();
  printf("loop retour\n");
  anal->CloseHisto();
  printf("close hist retour\n");
}

void analg4_ELoss() 
{
  /*
  It creates histograms of: 
  - energy loss by primary or by secondary particles for each event in the whole detector;
  - energy loss in the tracker by primary or by secondary particles;
  - energy loss in the calorimeter by primary or by secondary particles;
  - energy loss in the tracker or in the calo (by primary + secondary particles).
  */

  Analyzer* anal = new Analyzer(); 
  printf("set file chain\n");
  anal->SetFileChain("fichiers_test.txt");
  printf("set file chain retour\n");
  printf("init hist\n");
  anal->InitHisto_ELoss();
  printf("init hist retour\n");
  printf("loop\n");
  anal->Loop_ELoss();
  printf("loop retour\n");
  anal->CloseHisto_ELoss();
  printf("close hist retour\n");
}

void analg4_P_ELoss_Trk() 
{
  /*
  It creates histograms of:
  - energy loss in the tracker layer 1 and 2;
  - BetaGamma (obtained from the particle kinetic energy) for the tracker layer 1 and 2;
  - energy loss expressed in ADC counts in the tracker layer 1 (p and n channels) and 2 (p and n channels);
  - energy loss + average electronic noise expressed in ADC counts in the tracker layer 1 (p and n channels) and 2 (p and n channels).
  */

  Analyzer* anal = new Analyzer(); 
  printf("set file chain\n");
  anal->SetFileChain("fichiers_test.txt");
  printf("set file chain retour\n");
  printf("init hist\n");
  anal->InitHisto_P_ELoss_Trk();
  printf("init hist retour\n");
  printf("loop\n");
  anal->Loop_P_ELoss_Trk();
  printf("loop retour\n");
  anal->CloseHisto_P_ELoss_Trk();
  printf("close hist retour\n");
}

void analg4_acc_e() 
{
  /*
  Written by William
  */

  float energie = 10;
  Analyzer* anal = new Analyzer(); 
  //  anal->SetFile("file.root");
  printf("set file chain\n");
  anal->SetFileChain("fichiers_e_10MeV_ss.txt");
  printf("set file chain retour\n");
  printf("init hist e acc\n");
  anal->InitHisto_e_acc(energie);
  printf("init hist_e_acc retour\n");
  printf("loop\n");
  anal->Loop_acc();
  printf("loop acc retour\n");
  //  anal->CloseHisto_acc();
  //  printf("close hist retour\n");
}

void analg4_acc_p() 
{
  /*
  Written by William
  */

  float energie = 30;
  Analyzer* anal = new Analyzer(); 
  printf("set file chain\n");
  anal->SetFileChain("fichiers_p_30MeV_ams-farm.txt");
  printf("set file chain retour\n");
  printf("init hist e acc\n");
  anal->InitHisto_p_acc(energie);
  printf("init hist_p_acc retour\n");
  printf("loop\n");
  anal->Loop_acc();
  printf("loop acc retour\n");
  printf("close hist\n");
  anal->CloseHisto_acc();
  printf("close hist retour\n");
}

void analg4_acc_muon() 
{
  /*
  Written by William
  */

  Analyzer* anal = new Analyzer(); 
  printf("set file chain\n");
  anal->SetFileChain("fichiers_muon_acc.txt");
  printf("set file chain retour\n");
  printf("init hist muon acc\n");
  anal->InitHisto_Muon_acc();
  printf("init hist_muon_acc retour\n");
  printf("loop_muon\n");
  anal->Loop_muon();
  printf("loop muon retour\n");
  printf("close hist\n");
  anal->CloseHisto_Muon_acc();
  printf("close hist retour\n");
}

void tviewer() 
{
  //  TBrowser *tb = new TBrowser();
  gSystem->Load("libTreeViewer.so");
  new TTreeViewer();
  return;
}

void tbrowser() 
{
  TBrowser *tb = new TBrowser();
  //  gSystem->Load("libTreeViewer.so");
  //  new TTreeViewer();
  return;
}
